
create extension if not exists pgcrypto;

-- Bảng dữ liệu chính
create table if not exists public.classes(
  id uuid primary key default gen_random_uuid(),
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.classes add column if not exists is_active boolean not null default true;

create table if not exists public.groups(
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references public.classes(id) on delete cascade,
  name text not null,
  position int not null default 0,
  max_members int not null default 0 check(max_members >= 0),
  created_at timestamptz not null default now()
);

alter table public.groups add column if not exists max_members int not null default 0;
alter table public.groups drop constraint if exists groups_max_members_check;
alter table public.groups add constraint groups_max_members_check check(max_members >= 0);

create table if not exists public.members(
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references public.classes(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.member_weights(
  member_id uuid not null references public.members(id) on delete cascade,
  group_id uuid not null references public.groups(id) on delete cascade,
  percent numeric(5,2) not null default 0 check(percent between 0 and 100),
  primary key(member_id, group_id)
);

create table if not exists public.history(
  id bigint generated by default as identity primary key,
  class_id uuid not null references public.classes(id) on delete cascade,
  member_id uuid references public.members(id) on delete set null,
  group_id uuid references public.groups(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Cấu hình admin: chỉ lưu hash, không lưu mật khẩu thô
create table if not exists public.admin_settings(
  id integer primary key default 1 check(id=1),
  password_hash text not null,
  updated_at timestamptz not null default now()
);

-- Phiên đăng nhập admin
create table if not exists public.admin_sessions(
  token_hash text primary key,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '12 hours')
);

alter table public.classes enable row level security;
alter table public.groups enable row level security;
alter table public.members enable row level security;
alter table public.member_weights enable row level security;
alter table public.history enable row level security;
alter table public.admin_settings enable row level security;
alter table public.admin_sessions enable row level security;

-- Thành viên chỉ cần đọc dữ liệu để quay
drop policy if exists class_read on public.classes;
create policy class_read on public.classes for select to anon,authenticated
using (is_active = true);

drop policy if exists group_read on public.groups;
create policy group_read on public.groups for select to anon,authenticated using (true);

drop policy if exists member_read on public.members;
create policy member_read on public.members for select to anon,authenticated using (true);

drop policy if exists weight_read on public.member_weights;
create policy weight_read on public.member_weights for select to anon,authenticated using (true);

drop policy if exists history_insert on public.history;
create policy history_insert on public.history for insert to anon,authenticated with check (true);

-- Không cho client đọc trực tiếp mật khẩu/session
drop policy if exists admin_settings_no_read on public.admin_settings;
create policy admin_settings_no_read on public.admin_settings for select to anon,authenticated using (false);

drop policy if exists admin_sessions_no_read on public.admin_sessions;
create policy admin_sessions_no_read on public.admin_sessions for select to anon,authenticated using (false);

-- Đăng nhập admin bằng mật khẩu
create or replace function public.admin_login(p_password text)
returns text
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_hash text;
  v_token text;
begin
  select password_hash into v_hash
  from public.admin_settings
  where id = 1;

  if v_hash is null or p_password is null or v_hash <> crypt(p_password, v_hash) then
    raise exception 'INVALID_PASSWORD';
  end if;

  v_token := encode(gen_random_bytes(32), 'hex');

  insert into public.admin_sessions(token_hash, expires_at)
  values (
    encode(digest(v_token, 'sha256'), 'hex'),
    now() + interval '12 hours'
  );

  delete from public.admin_sessions where expires_at < now();

  return v_token;
end;
$$;

-- API admin duy nhất. Mọi thao tác CRUD đi qua đây.
create or replace function public.admin_api(
  p_token text,
  p_action text,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_ok boolean;
  v_id uuid;
  v_class_id uuid;
  v_group_id uuid;
  v_member_id uuid;
  v_name text;
  v_position integer;
  v_result jsonb;
  v_row jsonb;
  v_total numeric;
begin
  select exists(
    select 1 from public.admin_sessions
    where token_hash = encode(digest(coalesce(p_token,''), 'sha256'), 'hex')
      and expires_at > now()
  ) into v_ok;

  if not v_ok then
    return jsonb_build_object('error','INVALID_SESSION');
  end if;

  delete from public.admin_sessions where expires_at < now();

  case p_action

    when 'classes_list' then
      select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at), '[]'::jsonb)
      into v_result from public.classes x;
      return v_result;

    when 'class_add' then
      insert into public.classes(name, is_active)
      values (trim(p_payload->>'name'), true)
      returning id into v_id;
      return jsonb_build_object('id',v_id);

    when 'class_update' then
      update public.classes
      set name = trim(p_payload->>'name')
      where id = (p_payload->>'id')::uuid;
      return jsonb_build_object('ok',true);

    when 'class_delete' then
      delete from public.classes
      where id = (p_payload->>'id')::uuid;
      return jsonb_build_object('ok',true);

    when 'groups_list' then
      select coalesce(jsonb_agg(to_jsonb(x) order by x.position, x.created_at), '[]'::jsonb)
      into v_result from public.groups x
      where x.class_id = (p_payload->>'class_id')::uuid;
      return v_result;

    when 'group_add' then
      v_class_id := (p_payload->>'class_id')::uuid;
      select coalesce(max(position), -1) + 1 into v_position
      from public.groups where class_id = v_class_id;

      insert into public.groups(class_id,name,position,max_members)
      values(v_class_id,trim(p_payload->>'name'),v_position,greatest(0,coalesce((p_payload->>'max_members')::integer,0)))
      returning id into v_group_id;

      insert into public.member_weights(member_id,group_id,percent)
      select id,v_group_id,0 from public.members where class_id=v_class_id;

      return jsonb_build_object('id',v_group_id);

    when 'group_update' then
      update public.groups
      set name = trim(p_payload->>'name'),
          max_members = greatest(0, coalesce((p_payload->>'max_members')::integer, 0))
      where id = (p_payload->>'id')::uuid;
      return jsonb_build_object('ok',true);

    when 'group_delete' then
      delete from public.groups
      where id = (p_payload->>'id')::uuid;
      return jsonb_build_object('ok',true);

    when 'members_list' then
      select coalesce(jsonb_agg(to_jsonb(x) order by x.name), '[]'::jsonb)
      into v_result from public.members x
      where x.class_id = (p_payload->>'class_id')::uuid;
      return v_result;

    when 'member_add' then
      v_class_id := (p_payload->>'class_id')::uuid;

      insert into public.members(class_id,name)
      values(v_class_id,trim(p_payload->>'name'))
      returning id into v_member_id;

      select id into v_group_id
      from public.groups
      where class_id=v_class_id
      order by position,created_at
      limit 1;

      insert into public.member_weights(member_id,group_id,percent)
      select v_member_id,id,
             case when id=v_group_id then 100 else 0 end
      from public.groups
      where class_id=v_class_id;

      return jsonb_build_object('id',v_member_id);

    when 'member_update' then
      update public.members
      set name = trim(p_payload->>'name')
      where id = (p_payload->>'id')::uuid;
      return jsonb_build_object('ok',true);

    when 'member_delete' then
      delete from public.members
      where id = (p_payload->>'id')::uuid;
      return jsonb_build_object('ok',true);

    when 'weights_list' then
      select coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb)
      into v_result
      from public.member_weights x
      join public.members m on m.id=x.member_id
      where m.class_id=(p_payload->>'class_id')::uuid;
      return v_result;

    when 'weights_save' then
      for v_row in select * from jsonb_array_elements(coalesce(p_payload->'rows','[]'::jsonb))
      loop
        insert into public.member_weights(member_id,group_id,percent)
        values(
          (v_row->>'member_id')::uuid,
          (v_row->>'group_id')::uuid,
          (v_row->>'percent')::numeric
        )
        on conflict(member_id,group_id)
        do update set percent=excluded.percent;
      end loop;
      return jsonb_build_object('ok',true);

    when 'history_list' then
      select coalesce(jsonb_agg(
        jsonb_build_object(
          'id',h.id,
          'created_at',h.created_at,
          'member_name',m.name,
          'group_name',g.name
        ) order by h.created_at desc
      ), '[]'::jsonb)
      into v_result
      from public.history h
      left join public.members m on m.id=h.member_id
      left join public.groups g on g.id=h.group_id
      where h.class_id=(p_payload->>'class_id')::uuid
      limit 300;
      return v_result;

    when 'history_delete' then
      delete from public.history
      where class_id=(p_payload->>'class_id')::uuid;
      return jsonb_build_object('ok',true);

    else
      return jsonb_build_object('error','UNKNOWN_ACTION');
  end case;
end;
$$;

-- Đếm số thành viên đã được phân vào từng nhóm. 0 = không giới hạn.
create or replace function public.group_counts(p_class_id uuid)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select coalesce(jsonb_object_agg(group_id::text, member_count), '{}'::jsonb)
  from (
    select g.id as group_id, count(distinct h.member_id)::integer as member_count
    from public.groups g
    left join public.history h
      on h.group_id = g.id
     and h.class_id = p_class_id
    where g.class_id = p_class_id
    group by g.id
  ) x;
$$;

create or replace function public.member_assignment(p_class_id uuid, p_member_id uuid)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select coalesce(
    (select jsonb_build_object('group_id', h.group_id)
     from public.history h
     where h.class_id = p_class_id
       and h.member_id = p_member_id
     order by h.created_at desc
     limit 1),
    '{}'::jsonb
  );
$$;

grant execute on function public.group_counts(uuid) to anon, authenticated;
grant execute on function public.member_assignment(uuid,uuid) to anon, authenticated;

-- Cho phép trang GitHub Pages gọi 2 RPC
grant execute on function public.admin_login(text) to anon, authenticated;
grant execute on function public.admin_api(text,text,jsonb) to anon, authenticated;

-- Đặt mật khẩu admin lần đầu.
-- Nếu chạy lại dòng này, mật khẩu sẽ được đổi thành BuiAdmin@2026.
insert into public.admin_settings(id,password_hash)
values(1, crypt('BuiAdmin@2026', gen_salt('bf')))
on conflict(id) do update
set password_hash=excluded.password_hash,
    updated_at=now();
