-- GROUP PICKER - SUPABASE DATABASE
-- Chạy toàn bộ file này trong Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists classes (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists groups (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references classes(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists members (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references classes(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists member_weights (
  member_id uuid not null references members(id) on delete cascade,
  group_id uuid not null references groups(id) on delete cascade,
  percent numeric(5,2) not null default 0 check (percent >= 0 and percent <= 100),
  primary key(member_id, group_id)
);

create table if not exists history (
  id bigint generated by default as identity primary key,
  class_id uuid not null references classes(id) on delete cascade,
  member_id uuid references members(id) on delete set null,
  group_id uuid references groups(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Demo data
insert into classes(name)
select 'Lớp mẫu'
where not exists (select 1 from classes);

-- RLS
alter table classes enable row level security;
alter table groups enable row level security;
alter table members enable row level security;
alter table member_weights enable row level security;
alter table history enable row level security;

-- Demo: cho phép anon đọc/ghi.
-- Khi đưa website public thật, nên thay bằng Supabase Auth + RLS theo admin.
drop policy if exists "public classes" on classes;
create policy "public classes" on classes for all to anon using (true) with check (true);

drop policy if exists "public groups" on groups;
create policy "public groups" on groups for all to anon using (true) with check (true);

drop policy if exists "public members" on members;
create policy "public members" on members for all to anon using (true) with check (true);

drop policy if exists "public member_weights" on member_weights;
create policy "public member_weights" on member_weights for all to anon using (true) with check (true);

drop policy if exists "public history" on history;
create policy "public history" on history for all to anon using (true) with check (true);

-- Tạo nhanh nhóm/members bằng SQL nếu cần:
-- insert into groups(class_id, name) select id, 'Nhóm 1' from classes limit 1;
-- insert into groups(class_id, name) select id, 'Nhóm 2' from classes limit 1;
